### ISSUE TITLE
Linea del Tiempo Maribel Santiago Bautista 1BS

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-7-santiagomary1004#1]
[Actividad 7_Linea del tiempo_Maribel Santiago Bautista1BS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-santiagomary1004/files/9796913/Actividad.7_Linea.del.tiempo_Maribel.Santiago.Bautista1BS.pdf)

**Comment by ErikCuevas03** [comment]
Al estar dividido por fases se muestra una buena visibilidad dando una imagen mas limpia y legible

Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
